name: Deploy con SSH y Serveo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias necesarias
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Aceptar clave del host remoto
        run: |
          ssh-keyscan -p 22 serveo.net >> ~/.ssh/known_hosts
          ssh-keyscan -p 22 alex_vanguardia.serveo.net >> ~/.ssh/known_hosts

      - name: Desplegar archivos con SCP
        run: |
          scp -P 22 -o StrictHostKeyChecking=yes -r ./index.html ./styles.css ./script.js ./server.js ./package.json angel@alex_vanguardia.serveo.net:"C:/Users/Angel/Desktop/mi-web-cicd-test/"